### ISSUE TITLE
Unnecessary IOHIDDeviceScheduleWithRunLoop

### ISSUE THREAD

**Issue by geowar1** [slembcke/MacControllers#1]
According to the HID Manager technote (https://developer.apple.com/library/mac/technotes/tn2187/_index.html): By default when new devices are matched they are automatically scheduled with the same run loop as the HID Manager used to match the HID device (if it is scheduled with a run loop) in which case this additional step is unnecessary.

Otherwise excellent project! It sees my PS4 (which "just works!" (™, inc.)) and Xbox one (3rd party 360 driver) controllers. I'm recommending it to all the game developers I know. ;-)

**Comment by slembcke** [comment]
Good catch. I didn't see it mentioned from the API reference.

I'm pretty pumped about this myself. I've always loved the feel of game controllers, but supporting them in the past was always such a pain. Common, high quality controllers solve half of the problem. An API that treats them all more or less the same way solves the other half. (There's probably a third half that still needs solving, but I'm happy with the two.) Good to know that it works with Xbox One controllers, I don't have any of those to test with.

Feral Interactive has really good controller support in their games by providing mappings from a few dozen common models in plist files. I asked them if I could use their data, and they said yes. So I should be able to remove some of the hard coded parts. When I have the time anyway...

**Comment by geowar1** [comment]
> On Feb 17, 2015, at 8:01 AM, Scott Lembcke notifications@github.com wrote:
> Good catch. I didn't see it mentioned from the API reference.

Yeah, not mentioned there… I only knew about it because I had access to the sources when I wrote the technote. The other thing I mention is that developers don’t need to call IOHIDDeviceOpen on devices they get from the IOHIDManager… it’s only use case (that I can think of) is to close and re-open a device with different options (the default is to use what ever options were passed to the IOHIDManagerOpen call).

> I'm pretty pumped about this myself. I've always loved the feel of game controllers, but supporting them in the past was always such a pain. Common, high quality controllers solve half of the problem. An API that treats them all more or less the same way solves the other half. (There's probably a third half that still needs solving, but I'm happy with the two.) Good to know that it works with Xbox One controllers, I don't have any of those to test with.
> 
> Likewise here! I’ve been lobbying for a game controller API every since the Game Sprockets got the axe in the mid-90’s. I was very excited when it finally happened until I couldn’t find any game controllers that actually worked with it on OS X. Only recently (2 1/2 years since it’s release!) is there a game controller that’s supported on OS X (the Steel Series XL). I’ve spent the last 2 1/2 years lobbying for it to support the Xbox (360 and/or one) and PS (3 and/or 4) controllers. Those probably account for the vast majority of house holds that have game consoles (Ok, maybe the Nintendo Wii also…).
> Feral Interactive has really good controller support in their games by providing mappings from a few dozen common models in plist files. I asked them if I could use their data, and they said yes. So I should be able to remove some of the hard coded parts. When I have the time anyway…

My latest HID_Calibration sample project supports 32 controllers from 11 vendors (see the <HID_device_usage_strings.plist> file). I’m just using it to name the HID elements (buttons & axises) but entries could be added to map them to Game Controller gamepad elements.

Kuto's on getting the calibration code right. Most developers don’t realize that you can swap the logical values in order to flip the axis. Most developers also get the dead zone code wrong; they just truncate all values in the dead zone to the midpoint value. The step they miss is re-scaling the values outside the dead zone to go from the min/max values all the way to the midpoint value; not just to the dead zone values.

Luckily the HID Manager calibration code gets it right. ;-)

## 

Enjoy,
George Warner, (408)249-7533
eMail/iChat: geowar1@mac.com

**Comment by slembcke** [comment]
> I was very excited when it finally happened until I couldn’t find any game controllers that actually worked with it on OS X.

Yeah... The GCControllerDocs are really sparse about the details. It makes it sound like any MFi controller would work, but the Steel Series Stratus I have refuses to pair with my Mac for more than 10 seconds. Not even sure if it's supposed to work or not. On the other hand, I have a pile of console controllers that are higher quality anyway. I figured how hard could it be to hack support for them in. Turns out not very hard at all since the gamepad snapshots do most of the work. \o/

> My latest HID_Calibration sample project supports 32 controllers from 11 vendors (see the <HID_device_usage_strings.plist> file).

Where would I find that? That sounds useful to see. 

> Kuto's on getting the calibration code right.

Mostly I just rely on HID manager to "do the right thing". I didn't really think about it that hard. ;)

One thing I wasn't sure what to do with was the calibration saturation values. I get the feeling that actual console code hardcodes the ranges and assumes that controllers are always in good working order. I've also seen games that start with a small range and expand it when the input goes past those limits. This seems more correct in a way... since it will adapt to low quality or worn out controllers. On the other hand, it requires you to rotate the sticks around every time you start a game to calibrate them. Definitely annoying. The USB gamepads I had 10 years ago were bad enough that they required this. Even after calibration the precision was still poor though. On the other hand, it seems like it can be skipped for console controllers. Even my 6 year old, heavily used 360 controller seems to be fine. Hard-coding the ranges just feels wrong, but it seems like it's the best thing you can do?

**Comment by geowar1** [comment]
> On Feb 17, 2015, at 9:42 AM, Scott Lembcke notifications@github.com wrote:
> 
> > I was very excited when it finally happened until I couldn’t find any game controllers that actually worked with it on OS X.
> > Yeah... The GCControllerDocs are really sparse about the details. It makes it sound like any MFi controller would work, but the Steel Series Stratus I have refuses to pair with my Mac for more than 10 seconds. Not even sure if it's supposed to work or not. On the other hand, I have a pile of console controllers that are higher quality anyway. I figured how hard could it be to hack support for them in. Turns out not very hard at all since the gamepad snapshots do most of the work. \o/
> 
> I think that’s been the real hold up… OS X doesn’t implement MFI (yet?). So kinda by definition MFI controllers can’t work with OS X (unless the controller manufacturer specificly code their devices to work without MFI also). 
> My latest HID_Calibration sample project supports 32 controllers from 11 vendors (see the file).
> 
> Where would I find that? That sounds useful to see.
> 
> https://developer.apple.com/library/mac/samplecode/HID_Calibrator/Introduction/Intro.html
> 
> Kuto's on getting the calibration code right.
> 
> Mostly I just rely on HID manager to "do the right thing". I didn't really think about it that hard. ;)
> 
> That (in my definition) is “the right thing”… ;-)
> One thing I wasn't sure what to do with was the calibration saturation values. I get the feeling that actual console code hardcodes the ranges and assumes that controllers are always in good working order. I've also seen games that start with a small range and expand it when the input goes past those limits. This seems more correct in a way... since it will adapt to low quality or worn out controllers. On the other hand, it requires you to rotate the sticks around every time you start a game to calibrate them. Definitely annoying. The USB gamepads I had 10 years ago were bad enough that they required this. Even after calibration the precision was still poor though. On the other hand, it seems like it can be skipped for console controllers. Even my 6 year old, heavily used 360 controller seems to be fine. Hard-coding the ranges just feels wrong.

You can pass kIOHIDManagerOptionUsePersistentProperties to IOHIDManagerOpen and your (application specific) calibration settings will persist across applications launches (so you only have to calibrate the min/max saturation values on 1st launch).

## 

Enjoy,
George Warner, (408)249-7533
eMail/iChat: geowar1@mac.com
