### ISSUE TITLE
Solution for Mojave & Catalina?

### ISSUE THREAD

**Issue by latenitefilms** [slembcke/MacControllers#5]
@slembcke - I know this repository hasn't been updated for 4 years, however, I was just wondering if you ever came up with a workaround or solution for the fatal bug in `[GCControllerSnapshot snapshotData]`?

To give you some backstory - I'm really interested in adding game controller support to my open source application [CommandPost](https://commandpost.io), however Mojave doesn't support the Xbox Wireless Controller natively (only Catalina added support) so currently looking for suitable solution and came across this project.

Any words of wisdom you can share?

**Comment by slembcke** [comment]
Sadly no. I haven't even checked if they fixed the bug in the last year or two. :-\
